name = "Fabricate"
author = "spectrapulse"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba5b8bc3669683f80a715fa84df0c060f77ee368a7d970db36b38f28a93d575b"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
