name = "Fabricate"
author = "spectrapulse"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "318e1b5646f1ced8cad91194b832e1c2630aafacb5083a05f4a6096ce82c647a"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
