name = "Fabricate"
author = "spectrapulse"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3923ae1651d9d8c4800d3fd57ec2cf786fd842b0bb9bf8978cb7aebc36312729"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
