name = "Fabricate"
author = "spectrapulse"
version = "0.2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "729de53f012177742bc69f83d506db0de0b1a935caa7d6aff0c8e7bcb490b551"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
