name = "Fabricate"
author = "spectrapulse"
version = "0.2.8b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d85c757b59e64930aad00d93dce57369f06ce9f9e24b56160afcf514f177f18"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
