name = "Fabricate"
author = "spectrapulse"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e881eebe32e24ba39f08133380c352a3aee32458e414e7211460b425eb33398d"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
