name = "Fabricate"
author = "spectrapulse"
version = "0.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eba824ac7c87b001e78abe4e9d8dfe4a64918402d79f02a3231ebb8d162dae91"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
