name = "Fabricate"
author = "spectrapulse"
version = "0.2.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c93a7de1bc1133f8265b7aa85c1643d2e23fa2a6a85da598c285f5624980188f"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
