name = "Fabricate"
author = "spectrapulse"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9c5e9d9b09c4a1eef7d0a98d2a51b2a9d23eb6a504acdf24c769c789fd4cdfb"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
