name = "Fabricate"
author = "spectrapulse"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "401e461dc1779d49966569452883a90b3c54bd76d728311eb44a92910897d8a8"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
