name = "Fabricate"
author = "spectrapulse"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0875e758d984d70e514d97fe65e434d043c87e6dc0b1784a0d7183877669c88"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
