name = "Fabricate"
author = "spectrapulse"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f78cfb2a0d70ee7dc682dc3c4d9cbcfd9b7ac1b68cf4ce7c0fadaa5e1f847b94"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
