name = "Fabricate"
author = "spectrapulse"
version = "0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caf5b01469f046ccaf203b457e1b6d29821c62818fccd1de2a15538314403b20"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
