name = "Fabricate"
author = "spectrapulse"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86a411646f5212d45e926d0ec382c672daf1a03d2a15cf779944e6c44e5bd432"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
