name = "Fabricate"
author = "spectrapulse"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd114fc1a084c552a914b9d5e61b4f88c597cdf384eaebb67ec3c21519f45bb0"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
