name = "Fabricate"
author = "spectrapulse"
version = "0.2.8b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92527718a5859bae5b97de3ed0292cf08d585e406797b805af59294935e22b17"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
