name = "Fabricate"
author = "spectrapulse"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf4a2096c8039dfc365f71ce0bde7babb1af44a446f0fca24c4f8b55eff144d6"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
