name = "Fabricate"
author = "spectrapulse"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "880ec0166118107c29ae3e41bb42e5b12ddf8e0eb1a59c6590b79ec0df1e9879"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
