name = "Fabricate"
author = "spectrapulse"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f88405ef130974081fd3eacde8bc51271beb0219dea767f6481cbff202de270"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
