name = "Fabricate"
author = "spectrapulse"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64773ada226848018efabfe73b903ea8a199ef8d844af3a5f1c3090a788ea439"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
