name = "Fabricate"
author = "spectrapulse"
version = "0.2.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57941ced34a212c80a04c0e75bbc4144e500627a658c1b30eb62192721b268c4"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
