name = "Fabricate"
author = "spectrapulse"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41b99a6149e0b88b7bcf2d1eb2692c36aa52e02c83ebbd919903310114140474"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
