name = "Fabricate"
author = "spectrapulse"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70c3681927119207236952cc5d9559d616f58816b41f754fe1e2fca2d13fcffa"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
