name = "Fabricate"
author = "spectrapulse"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a9a0aac7158901ba82465f2c2916739c3a99ed532d4265cd0522b9497bf59ce"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
