name = "Fabricate"
author = "spectrapulse"
version = "0.2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75a306b34f81030c9588307ff78bc1a6f12acf96048a7e5bbcd76cb0f17d2d47"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
