name = "Fabricate"
author = "spectrapulse"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2f4ef976ff610e45bc1fdfe1d9a35d1ff58fe7003b11bb9a3ce46cc43328d91"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
