name = "Fabricate"
author = "spectrapulse"
version = "0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d5a1d66d89ae83bbcbcb35a780abbc5312dcccd0c06ce1815ba79488bdaad39"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
