name = "Fabricate"
author = "spectrapulse"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8a7f7d79af57fecfc200ec84f76e9c8f6a5008a19a5219ed5cfef184bfe356a"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
