name = "Fabricate"
author = "spectrapulse"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91f39cd9cb536fb38a5f7590ea431d23fd8a1400c94b93760470ee7828209678"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
