name = "Fabricate"
author = "spectrapulse"
version = "0.2.9b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "615fd3a020b515930b8960d7aca43b5f27b7b2b62948e3ff0a4b802fb76fb648"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
