name = "Fabricate"
author = "spectrapulse"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdb026c70a7cad13dd682d65df54a36f2f8476fd97d85ae3bf35337d82720fe2"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
