name = "Fabricate"
author = "spectrapulse"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f41561bfeeea757207bfd1b197270afc84800b26f7697854bb219f44ebcf7db"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
