name = "Fabricate"
author = "spectrapulse"
version = "0.2.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b652b906fe40eb14bc12bdf382ad3645e1084be82826461369b4c41ecd3b3ef9"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
